pipeline:
  identifier: Build_Azaar_Mahill_learn_with_krish_1705478708457
  name: Build learn-with-krish
  orgIdentifier: default
  projectIdentifier: myFirstProject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1705478649019
        repoName: Azaar-Mahill/learn-with-krish
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
